apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
  selector:
    name: roboshop
    componentname: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
